{% set name = "dqsegdb" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: acb30f22a8028d800fa39423c2f7ec37bbfbc26bfd05809a5d60e3771859ecab
  patches:
    # clean requirements for conda-forge
    #   - don't require 'lalsuite', we only need lal
    - requirements.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - gwdatafind
    - ligo-segments
    - lscsoft-glue >=3.0.1
    - pyopenssl >=0.14
    - pyrxp
    - python
    - python-lal
    - six

test:
  requires:
    - pip
    - pytest
  imports:
    - dqsegdb
    - dqsegdb.apicalls
    - dqsegdb.clientutils
    - dqsegdb.jsonhelper
    - dqsegdb.urifunctions
  commands:
    # check requirements
    - python -m pip check
    # run test suite
    - python -m pytest -ra -v --pyargs dqsegdb.tests
    # check scripts
    - ligolw_dq_query_dqsegdb --help
    - ligolw_publish_threaded_dqxml_dqsegdb --help
    - ligolw_segment_insert_dqsegdb --help
    - ligolw_segment_query_dqsegdb --help
    - ligolw_segments_from_cats_dqsegdb --help

about:
  home: https://github.com/ligovirgo/dqsegdb/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Client library for DQSegDB

extra:
  recipe-maintainers:
    - duncanmmacleod
    - rpfisher
    - robertbruntz
