{% set name = "dqsegdb" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 130e01427bdc7a5b404a84d1dcfc5c61fc3522427955d24c63ece2b037a4725d

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - gwdatafind
    - ligo-segments
    - lscsoft-glue >=1.55.0
    - pyopenssl >=0.14
    - pyrxp
    - python
    - python-lal
    - six

test:
  imports:
    - dqsegdb
    - dqsegdb.apicalls
    - dqsegdb.clientutils
    - dqsegdb.jsonhelper
    - dqsegdb.urifunctions
  commands:
    - ligolw_dq_query_dqsegdb --help
    - ligolw_publish_threaded_dqxml_dqsegdb --help
    - ligolw_segment_insert_dqsegdb --help
    - ligolw_segment_query_dqsegdb --help
    - ligolw_segments_from_cats_dqsegdb --help

about:
  home: https://github.com/ligovirgo/dqsegdb/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Client library for DQSegDB

extra:
  recipe-maintainers:
    - duncanmmacleod
    - rpfisher
    - robertbruntz
