{% set name = "dqsegdb" %}
{% set version = "1.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b0a0834d27aeb8bf789b532d623ddba2edd9c0f791ad7080b1b418abb4c395d3

build:
  number: 0
  skip: true  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - gwdatafind
    - ligo-segments
    - lscsoft-glue >=1.55.0
    - pyopenssl >=0.14
    - pyrxp
    - python-lal
    - six

test:
  imports:
    - dqsegdb
    - dqsegdb.apicalls
    - dqsegdb.clientutils
    - dqsegdb.jsonhelper
    - dqsegdb.urifunctions
  commands:
    - ligolw_dq_query_dqsegdb --help
    - ligolw_publish_threaded_dqxml_dqsegdb --help
    - ligolw_segment_insert_dqsegdb --help
    - ligolw_segment_insert_dqsegdb --help
    - ligolw_segment_query_dqsegdb --help
    - ligolw_segments_from_cats_dqsegdb --help

about:
  home: https://github.com/ligovirgo/dqsegdb/
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: Client library for DQSegDB

extra:
  recipe-maintainers:
    - duncanmmacleod
    - rpfisher
